### ISSUE TITLE
feature request:

### ISSUE THREAD

**Issue by dangeles** [slowkow/harmonypy#14]
Hey! Thank you so much for porting harmony into python -- it's super useful.

I had one feature request that I wanted to make, in case others found it useful: Is there any chance you could include support for multiple covariates? It would make `harmonypy` even more useful and powerful, but I haven't been able to find out whether this is already supported as is by the current program base.

Thank you again for this wonderful contribution!
David

**Comment by slowkow** [comment]
Thanks for the question, David!

I believe that multiple covariates should be working OK starting with version 0.0.4. See this previous issue for details: https://github.com/slowkow/harmonypy/issues/4

Let me know if you run into any issues.

I am starting to get the hint that the documentation for harmonypy could use some improvement 🙂

**Comment by dangeles** [comment]
You are totally right. I tried it and it worked like a charm. Thank you for the prompt reply!
