### ISSUE TITLE
Unique key is not in pandas describe

### ISSUE THREAD

**Issue by Arkkienkeli** [slowkow/harmonypy#22]
Hi, I guess in this line should be an option `include='all'` for `describe()` method. 
https://github.com/slowkow/harmonypy/blob/18a4f02bca0f83b35d156d442bd7a8b7e16155b6/harmonypy/harmony.py#L88

Otherwise there is an error 
```
     86 
     87     phi = pd.get_dummies(meta_data[vars_use]).to_numpy().T
---> 88     phi_n = meta_data[vars_use].describe().loc['unique'].to_numpy().astype(int)
     89 
     90     if theta is None:

KeyError: 'unique'
```

**Comment by Arkkienkeli** [comment]
Turns out if metadata column datatype is not `str`, then `unique` won't work properly. 
No need to change, leaving this as a reference if someone will have the same problem.
Solution is to make sure that metadata columns used are of `str` type.

**Comment by jeskowagner** [comment]
Just ran into the same thing and arrive at the same conclusion. Note that datatype `category` will also do the job (and save memory if you have few batches). Perhaps the offending line could be changed to `np.unique(meta_data[vars_use].shape[0]` to avoid this issue?
