### ISSUE TITLE
Failed to set number of max iterations to more than 10

### ISSUE THREAD

**Issue by liboxun** [slowkow/harmonypy#3]
When I tried to run Harmony using: 

`hm.run_harmony(data_mat, meta_data, vars_use, max_iter_harmony=50)`

It still only ran 10 iterations and stopped prematurely before reaching convergence. Any idea how to harmonize a dataset with > 10 iterations? 

Thanks in advance!

**Comment by slowkow** [comment]
Thanks for reporting the issue! I hope that the latest commit fixes it.

Could I please ask if you might be able to test the latest version from Github?

```bash
pip install git+https://github.com/slowkow/harmonypy
```

**Comment by liboxun** [comment]
This update (0.0.4) fixed it! Thanks!
