### ISSUE TITLE
Reference mapping option

### ISSUE THREAD

**Issue by dhoanghiep** [slowkow/harmonypy#30]
Hi,

when reviewing run_harmony(), I found that `reference_values` is available as a keyword argument. However, `reference_values` is not referenced anywhere in the function and also does not appear in the Harmony class. I wonder if this feature of reference mapping was implemented in harmonypy.

Thank you

**Comment by slowkow** [comment]
No, `reference_values` is not used in the current version of harmonypy. Interested readers should study the [R source code](https://github.com/immunogenomics/harmony/blob/master/R/ui.R) to understand this option.

**Comment by slowkow** [comment]
Pull requests are welcome. Feel free to open another issue if you have more questions.
