### ISSUE TITLE
Any plan to release 0.0.10 ?

### ISSUE THREAD

**Issue by johnarevalo** [slowkow/harmonypy#35]
These commits have been there for a while. It'd be nice to have a `pip install`able named version including these last changes.

https://github.com/slowkow/harmonypy/compare/v0.0.9...master

**Comment by slowkow** [comment]
You're right, thanks for the reminder.

**Comment by slowkow** [comment]
Hey @johnarevalo, I made a new tag for 0.0.10 and published it to PyPI.

I tried poetry and gave up when I encountered endless errors about dependency versions. 

Then I tried hatch and everything just worked, first try.

You are now listed in the pyproject.toml file, so let me know if you're OK with that, or if you want to change how your name appears. In R packages, for example, I know we can add ORCID identifiers. I don't know about Python packages.

This commit shows what I did to migrate from setup.py to hatch: https://github.com/slowkow/harmonypy/commit/a770f2dd3b724a7b5dae811357bd157cedacc195

**Comment by johnarevalo** [comment]
I'm glad to be mentioned, Thank you! I created #36 adding my email.

**Comment by johnarevalo** [comment]
Great! I saw that `0.0.10` is also available in [bioconda](https://anaconda.org/bioconda/harmonypy)!

It be nice to create a release in https://github.com/slowkow/harmonypy/releases, to avoid confusion on what is the latest version available.
