### ISSUE TITLE
How to cite this work?

### ISSUE THREAD

**Issue by burtonrj** [slowkow/harmonypy#9]
Hi,

Thank you so much for this contribution to the Python ecosystem. I've been applying your implementation of Harmony to cytometry data with some success after hyperparameter tuning and normalisation. I was wondering how best to cite your work? I had planned on citing the original Harmony paper but would also like to give credit to your library.

**Comment by slowkow** [comment]
Ross, thank you so much for the thoughtful question!

I agree with you that it is appropriate to cite the original Harmony paper:

> Korsunsky, I. et al. Fast, sensitive and accurate integration of single-cell data with Harmony. Nat. Methods (2019) doi:10.1038/s41592-019-0619-0

Just a few minutes ago, I managed to upload harmonypy 0.0.5 to Zenodo ([link](https://zenodo.org/record/4531401)).

So, to cite the harmonypy Python package, we can write something like this:

> Kamil Slowikowski. (2020, August 11). slowkow/harmonypy: harmonypy version 0.0.5 (Version v0.0.5). Zenodo. http://doi.org/10.5281/zenodo.4531401

Here's the BibTex version:

```
@software{kamil_slowikowski_2020_4531401,
  author       = {Kamil Slowikowski},
  title        = {slowkow/harmonypy: harmonypy version 0.0.5},
  month        = aug,
  year         = 2020,
  publisher    = {Zenodo},
  version      = {v0.0.5},
  doi          = {10.5281/zenodo.4531401},
  url          = {https://doi.org/10.5281/zenodo.4531401}
}
```

I also noticed that the Zenodo website has a nice feature all the way at the bottom of the page to reformat the citation for a particular journal:

<img src="https://user-images.githubusercontent.com/209714/107545162-f97f4280-6b98-11eb-85aa-dfac21110efd.jpg" width="30%">

**Comment by burtonrj** [comment]
Amazing! Thank you.
